version: "3"
services:
  node:
    build:
      context: ./node
      dockerfile: ./Dockerfile
    command: node /src/index.js
    restart: always
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    command: service nginx start
    depends_on:
      - node
    ports:
      - "7080:80"
    restart: always